from __future__ import annotations

import argparse
import json
import os
import zipfile
from collections import Counter
from pathlib import Path


IMAGE_EXTENSIONS = {".jpeg", ".jpg", ".png"}
CLASS_DIRS = ("NORMAL", "PNEUMONIA")
DEFAULT_DATASET_ROOT = Path("data/raw/chest_xray")
DEFAULT_OUTPUT_PATH = Path("data/processed/prepare_report.json")
KAGGLE_DATASET = "paultimothymooney/chest-xray-pneumonia"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Download (if needed) and validate a local Kaggle Chest X-Ray dataset and write a preparation report."
    )
    parser.add_argument(
        "--dataset-root",
        default=str(DEFAULT_DATASET_ROOT),
        help="Path to the extracted Kaggle chest_xray dataset root.",
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT_PATH),
        help="Path to the JSON report generated by prepare.py.",
    )
    parser.add_argument(
        "--no-download",
        action="store_true",
        help="Skip dataset download if it doesn't exist (validation only).",
    )
    return parser.parse_args()


def check_kaggle_credentials() -> bool:
    """Check if kaggle.json exists in ~/.kaggle/"""
    kaggle_json = Path.home() / ".kaggle" / "kaggle.json"
    if not kaggle_json.exists():
        return False
    # Set Kaggle config directory
    os.environ["KAGGLE_CONFIG_DIR"] = str(kaggle_json.parent)
    return True


def download_dataset(dataset_root: Path) -> None:
    """Download dataset from Kaggle using kaggle CLI."""
    if not check_kaggle_credentials():
        raise FileNotFoundError(
            "Kaggle credentials not found. Please place kaggle.json at ~/.kaggle/kaggle.json\n"
            "Download it from: https://www.kaggle.com/settings/account"
        )
   
    try:
        import kaggle
    except ImportError:
        raise ImportError(
            "kaggle package not installed. Install it with: pip install kaggle"
        )
   
    # Create parent directory
    dataset_root.parent.mkdir(parents=True, exist_ok=True)
   
    print(f"Downloading Kaggle dataset: {KAGGLE_DATASET}")
    print(f"Destination: {dataset_root}")
   
    try:
        kaggle.api.dataset_download_files(
            KAGGLE_DATASET,
            path=dataset_root.parent,
            unzip=True
        )
        print("✓ Dataset downloaded and extracted successfully")
    except Exception as e:
        raise RuntimeError(f"Failed to download dataset: {e}")


def infer_label(path: Path) -> str:
    if path.parent.name == "NORMAL":
        return "Normal"
    filename = path.name.lower()
    if "bacteria" in filename:
        return "Bacterial"
    if "virus" in filename:
        return "Viral"
    raise ValueError(f"Could not infer pneumonia subtype from filename: {path}")


def collect_split(split_dir: Path) -> dict:
    images = []
    labels = []

    for class_dir in CLASS_DIRS:
        folder = split_dir / class_dir
        if not folder.exists():
            continue
        for path in sorted(folder.iterdir()):
            if path.suffix.lower() in IMAGE_EXTENSIONS:
                images.append(str(path))
                labels.append(infer_label(path))

    return {
        "num_images": len(images),
        "label_distribution": dict(Counter(labels)),
        "sample_paths": images[:5],
    }


def validate_dataset_root(dataset_root: Path) -> None:
    """Validate that dataset structure is correct."""
    if not dataset_root.exists():
        raise FileNotFoundError(
            f"Dataset root not found: {dataset_root}. "
            "Run without --no-download flag to auto-download, or download manually from Kaggle."
        )

    missing = [split for split in ("train", "val", "test") if not (dataset_root / split).exists()]
    if missing:
        raise FileNotFoundError(
            f"Dataset root is missing expected split folders: {', '.join(missing)}"
        )


def main():
    args = parse_args()
    dataset_root = Path(args.dataset_root).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    # Download dataset if it doesn't exist
    if not dataset_root.exists():
        if args.no_download:
            raise FileNotFoundError(
                f"Dataset not found at {dataset_root} and --no-download flag was set."
            )
        print("Dataset not found. Attempting to download from Kaggle...")
        download_dataset(dataset_root)

    # Validate dataset structure
    validate_dataset_root(dataset_root)

    # Generate report
    report = {
        "dataset_root": str(dataset_root),
        "splits": {
            split: collect_split(dataset_root / split) for split in ("train", "val", "test")
        },
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2, sort_keys=True))

    print(f"✓ Prepared dataset report at: {output_path}")
    for split, split_report in report["splits"].items():
        print(
            f"  {split}: {split_report['num_images']} images | "
            f"{split_report['label_distribution']}"
        )


if __name__ == "__main__":
    main()