from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path


IMAGE_EXTENSIONS = {".jpeg", ".jpg", ".png"}
CLASS_DIRS = ("NORMAL", "PNEUMONIA")
DEFAULT_DATASET_ROOT = Path("data/raw/chest_xray")
DEFAULT_OUTPUT_PATH = Path("data/processed/prepare_report.json")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Validate a local Kaggle Chest X-Ray dataset and write a small preparation report."
    )
    parser.add_argument(
        "--dataset-root",
        default=str(DEFAULT_DATASET_ROOT),
        help="Path to the extracted Kaggle chest_xray dataset root.",
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT_PATH),
        help="Path to the JSON report generated by prepare.py.",
    )
    return parser.parse_args()


def infer_label(path: Path) -> str:
    if path.parent.name == "NORMAL":
        return "Normal"
    filename = path.name.lower()
    if "bacteria" in filename:
        return "Bacterial"
    if "virus" in filename:
        return "Viral"
    raise ValueError(f"Could not infer pneumonia subtype from filename: {path}")


def collect_split(split_dir: Path) -> dict:
    images = []
    labels = []

    for class_dir in CLASS_DIRS:
        folder = split_dir / class_dir
        if not folder.exists():
            continue
        for path in sorted(folder.iterdir()):
            if path.suffix.lower() in IMAGE_EXTENSIONS:
                images.append(str(path))
                labels.append(infer_label(path))

    return {
        "num_images": len(images),
        "label_distribution": dict(Counter(labels)),
        "sample_paths": images[:5],
    }


def validate_dataset_root(dataset_root: Path) -> None:
    if not dataset_root.exists():
        raise FileNotFoundError(
            f"Dataset root not found: {dataset_root}. "
            "Download/extract the Kaggle dataset to data/raw/chest_xray first."
        )

    missing = [split for split in ("train", "val", "test") if not (dataset_root / split).exists()]
    if missing:
        raise FileNotFoundError(
            f"Dataset root is missing expected split folders: {', '.join(missing)}"
        )


def main():
    args = parse_args()
    dataset_root = Path(args.dataset_root).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    validate_dataset_root(dataset_root)

    report = {
        "dataset_root": str(dataset_root),
        "splits": {
            split: collect_split(dataset_root / split) for split in ("train", "val", "test")
        },
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2, sort_keys=True))

    print(f"Prepared dataset report at: {output_path}")
    for split, split_report in report["splits"].items():
        print(
            f"{split}: {split_report['num_images']} images | "
            f"{split_report['label_distribution']}"
        )


if __name__ == "__main__":
    main()

